name: "Release Homebrew"

on:
  release:
    types: [published]

jobs:
  homebrew:
    runs-on: ubuntu-20.04
    steps:
      - name: Update Homebrew formula
        uses: dawidd6/action-homebrew-bump-formula@baf2b60c51fc1f8453c884b0c61052668a71bd1d # v3.11.0
        with:
          token: ${{ secrets.HOMEBREW_TOKEN }}
          org: anchore
          formula: syft

      - uses: 8398a7/action-slack@fbd6aa58ba854a740e11a35d0df80cb5d12101d8 #v3.15.1
        if: ${{ failure() }}
        with:
          status: ${{ job.status }}
          fields: repo,workflow,action,eventName
          text: "Post-release homebrew publish workflow has failed: https://github.com/anchore/syft/actions/workflows/release-homebrew.yaml"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_TOOLBOX_WEBHOOK_URL }}
